package com.promptgallery.data.local.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * The central record of the application. Each row represents one AI-generated
 * image together with the prompt(s) and generation metadata that produced it.
 *
 * The binary image and its thumbnail are stored on disk in app-private storage;
 * only their paths are kept in the database to keep the table small and fast.
 */
@Entity(
    tableName = "images",
    foreignKeys = [
        ForeignKey(
            entity = FolderEntity::class,
            parentColumns = ["id"],
            childColumns = ["folderId"],
            onDelete = ForeignKey.SET_NULL,
        ),
    ],
    indices = [
        Index("folderId"),
        Index("isFavorite"),
        Index("rating"),
        Index("colorLabel"),
        Index("aiModel"),
        Index("creationDate"),
        Index("importDate"),
        Index("modifiedDate"),
    ],
)
data class ImageEntity(
    @PrimaryKey
    val id: String,

    /** Absolute path of the full-resolution image inside app-private storage. */
    val filePath: String,
    /** Original file name as imported, preserved for export. */
    val fileName: String,
    /** Absolute path of the generated thumbnail. */
    val thumbnailPath: String,

    val title: String = "",
    val description: String = "",

    /** The positive prompt. Indexed by FTS for search. */
    val prompt: String = "",
    val negativePrompt: String = "",

    /** Generation tool, e.g. "Midjourney", "Flux", "Stable Diffusion". */
    val aiModel: String = "",

    /** Human-readable aspect ratio label, e.g. "1:1", "16:9". */
    val aspectRatio: String = "",
    val width: Int = 0,
    val height: Int = 0,

    val seed: Long? = null,
    val sampler: String = "",
    val cfg: Float? = null,
    val steps: Int? = null,

    @ColumnInfo(defaultValue = "0")
    val isFavorite: Boolean = false,
    /** 0 = unrated, 1..5 stars. */
    @ColumnInfo(defaultValue = "0")
    val rating: Int = 0,
    /** Stored as the name of [com.promptgallery.domain.model.ColorLabel]. */
    @ColumnInfo(defaultValue = "'NONE'")
    val colorLabel: String = "NONE",

    val folderId: String? = null,
    val customNotes: String = "",
    val sourceUrl: String = "",

    /** When the image was generated by the source tool (epoch millis). */
    val creationDate: Long,
    /** When the image was imported into the app (epoch millis). */
    val importDate: Long,
    /** Last time any field of this record changed (epoch millis). */
    val modifiedDate: Long,

    val fileSize: Long = 0,
    val mimeType: String = "image/png",
)
